### ISSUE TITLE
URL di dati.lombardia.it

### ISSUE THREAD

**Issue by dcrespi** [opendatalombardia/lariachetira#1]
l'URL corretto è www.dati.lombardia.it

dati.lombardia.it è un redirect rimasto per compatibilità,
meglio mettere l'URL giusto

grazie
daniele

**Comment by nelsonmau** [comment]
ciao @dcrespi,

ok ma non ho capito esattamente a quale pagina/luogo ti riferisci in cui c'è l'errore. Riesci a mettermi un link qui?
grazie!

**Comment by dcrespi** [comment]
In fondo alla pagina de l'ariachetira dove ci sono i riferimenti ai siti

Daniele Crespi

Il 28/nov/2016 18:48, "Andrea Nelson Mauro" <notifications@github.com> ha
scritto:

**Comment by nelsonmau** [comment]
@dcrespi check please, ora dovrebbe essere ok

**Comment by dcrespi** [comment]
ora è OK  :-)

2016-11-29 19:36 GMT+01:00 Andrea Nelson Mauro <notifications@github.com>:

**Comment by nelsonmau** [comment]
E allora puoi chiudere la issue! Un piccolo gesto per l'uomo, un grande gesto nel mondo del web! :-)
